services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: redis
    ports:
      - 6378:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
  todo-backend-dev:
    image: todo-backend-dev-image
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/test
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./todo-backend/:/usr/src/app
    depends_on:
      - mongo
      - redis

  todo-frontend-dev:
    image: todo-frontend-dev-image
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-frontend-dev

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend-dev
      - todo-backend-dev
