services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js 
  redis:
    image: redis
    ports:
      - 6378:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
  express:
    image: todo-backend-dev-image
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/test
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
      - redis
